.TH "src/main/cpp/Robot.cpp" 3 "Wed Dec 12 2018" "BaseBot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/cpp/Robot.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Robot\&.h'\fP
.br
\fC#include <Commands/Scheduler\&.h>\fP
.br
\fC#include <SmartDashboard/SmartDashboard\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSetCycleTime\fP (double seconds)"
.br
.ti -1c
.RI "double \fBGetCycleTime\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double GetCycleTime ()"

.PP
Definition at line 119 of file Robot\&.cpp\&.
.SS "void SetCycleTime (double seconds)"

.PP
Definition at line 103 of file Robot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BaseBot from the source code\&.
